services:
  server:
    image: sample:latest
    environment:
      NODE_ENV: production
      QDRANT_URL: http://qdrant:6333
      MYSQL_URL: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: super_secret_pass

    ports:
      - 3000:3000

  qdrant:
    image: qdrant/qdrant:v1.4.0
    restart: always
    ports:
      - 6333:6333

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: super_secret_pass
    ports:
      - 3306:3306
